console.log("tesst git ")
console.log(123)
console.log('345')
console.log('5678')
console.log('test1')
console.log('details')
console.log('detai1')
console.log('detai2')
console.log('detail3')
console.log('1')
console.log(2)
console.log(3)
console.log(4)
console.log(5)
